### ISSUE TITLE
🌐 We need English

### ISSUE THREAD

**Issue by NoNormalCreeper** [Ink-33/OhMyStream9#1]
Hey bro, it's such an awesome project! But we need **an English translation**. I'll be very appreciative if do so.

**Comment by Ink-33** [comment]
Unfortunately, we don't have enough manpower to complete the task. 

As you can see, English version is still WIP.
 
Thus, if you would like to help me, I would be very grateful.

**Comment by NoNormalCreeper** [comment]
🥰Thanks for your attention and reply!
I'll help you as much as I can.
